CREATE TABLE DIA
(
  COD_DIA INT,   
  DESCRIPCION VARCHAR(20)   NOT NULL,
Primary key (COD_DIA)  
);

CREATE TABLE MEDIOS_DE_PAGO
(
  COD_MEDIO     INT,
  DESCRIPCION   VARCHAR(30)      NOT NULL,
Primary key (COD_MEDIO)

);

CREATE TABLE VENDEDORES
(
  COD_VENDEDOR   INT,
  NOMBRE         VARCHAR(30)     NOT NULL,
Primary key (COD_VENDEDOR)

);

CREATE TABLE VENTAS_C
(
  N_FACTURA     VARCHAR(50)   NOT NULL,
  TIPO_FACTURA  CHAR(1)       NOT NULL,
  FECHA         DATE          NOT NULL,
  COD_CLIENTE   INT   NULL,
  TURNO         VARCHAR(50)   NULL,
  COD_DIA       INT           NULL,
  COD_MEDIO_PAGO INT NOT NULL,
  COD_VENDEDOR   INT NOT NULL,
Primary key (N_FACTURA,TIPO_FACTURA) ,
Foreign Key (COD_DIA) references DIA(COD_DIA),
Foreign Key (COD_MEDIO_PAGO) references MEDIOS_DE_PAGO(COD_MEDIO),
Foreign Key (COD_VENDEDOR)   references VENDEDORES(COD_VENDEDOR),
Foreign Key (COD_CLIENTE)   references CLIENTES(COD_CLIENTE)
);

CREATE TABLE ARTICULOS
(
  COD_ARTICULO    INT,   
  DESCRIPCION     VARCHAR(50)  NOT NULL,
  COLOR           VARCHAR(50)  NOT NULL,
  TALLE           VARCHAR(10)  NULL,
  
Primary Key (COD_ARTICULO) 
);


CREATE TABLE VENTAS_D
(
  N_FACTURA      VARCHAR(50)  NOT NULL,
  TIPO_FACTURA   CHAR(1)      NOT NULL,
  COD_ARTICULO   INT          NOT NULL,
  CANTIDAD       INT          NOT NULL,
  PRECIO_UNIDAD  DECIMAL(2)   NOT NULL,
Primary key (N_FACTURA,TIPO_FACTURA) ,
Foreign Key (COD_ARTICULO) references ARTICULOS(COD_ARTICULO)

);


CREATE TABLE LOCALIDADES
(
  COD_LOCALIDAD   INT,
  DESCRIPCION     VARCHAR(30)    NOT NULL,
Primary key (COD_LOCALIDAD)

);

CREATE TABLE CLIENTES
(
  COD_CLIENTE   INT,
  NOMBRE        VARCHAR(30)      NOT NULL,
  APELLIDO      VARCHAR(30)      NULL,
  DNI           VARCHAR(30)      NULL,
  COD_LOCALIDAD INT NULL,
  TELEFONO      VARCHAR(30)      NULL,
  MAIL          VARCHAR(50)      NULL,
Primary key (COD_CLIENTE),
Foreign Key (COD_LOCALIDAD)   references LOCALIDADES(COD_LOCALIDAD)
);

CREATE TABLE PROVEEDORES
(
  COD_PROVEEDOR  INT,
  NOMBRE         VARCHAR(30)     NOT NULL,
  APELLIDO       VARCHAR(30)     NOT NULL,
  DNI            VARCHAR(30)     NULL,
  COD_LOCALIDAD  INT NOT NULL,
  TELEFONO       VARCHAR(30)     NULL,
  MAIL           VARCHAR(50)     NULL,
Primary key (COD_PROVEEDOR)

);

CREATE TABLE COMPRAS_C
(
  N_COMPRA        INT,
  N_FACTURA       VARCHAR(50)   NOT NULL,
  FECHA           DATE          NOT NULL,
  COD_PROVEEDOR   INT           NOT NULL,
  COD_DIA         INT           NULL,
  COD_MEDIO_PAGO  INT           NOT NULL,
  COD_COMPRADOR   INT           NOT NULL,
Primary key (N_COMPRA) ,
Foreign Key (COD_DIA) references DIA(COD_DIA),
Foreign Key (COD_MEDIO_PAGO) references MEDIOS_DE_PAGO(COD_MEDIO),
Foreign Key (COD_COMPRADOR)   references COMPRADORES(COD_COMPRADOR),
Foreign Key (COD_PROVEEDOR)   references PROVEEDORES(COD_PROVEEDOR)
);

CREATE TABLE COMPRAS_D
(
  N_COMPRA        INT,
  COD_ARTICULO    INT,           
  CANTIDAD        INT NOT NULL,
  PRECIO_UNIDAD   DECIMAL(2),
Primary key (N_COMPRA, COD_ARTICULO) ,
Foreign Key (COD_ARTICULO) references ARTICULOS(COD_ARTICULO)

);

CREATE TABLE STOCK
(
  COD_ARTICULO        INT,
  FECHA_INGRESO       DATE          NOT NULL,
  CANTIDAD            INT           NOT NULL,
  CANTIDAD_MINIMA     INT           NOT NULL,
Primary key (COD_ARTICULO,FECHA_INGRESO) ,
Foreign Key (COD_ARTICULO) references ARTICULOS(COD_ARTICULO)

);

CREATE TABLE BANCO
(
  COD_BANCO      INT,
  DESCRIPCION    VARCHAR(30)     NOT NULL,
Primary key (COD_BANCO)

);


CREATE TABLE INVERSION
(
  COD_BANCO       INT,
  FECHA_INICIO    DATE,
  MONTO           DECIMAL(2)      NOT NULL,
  PLAZO_DIAS      INT             NOT NULL,
  N_CUENTA        VARCHAR(30)     NULL,
Primary key (COD_BANCO,FECHA_INICIO) ,
Foreign Key (COD_BANCO) references BANCO(COD_BANCO)

);

